version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install -r requirements.txt -t lib
  build:
    commands:
      - cd lib
      - zip -r9 ../deploy.zip .
      - cd ..
      - zip -g deploy.zip lambda_function.py
  post_build:
    commands:
      - aws lambda update-function-code --function-name test --zip-file fileb://deploy.zip